### ISSUE TITLE
Instructions for SSL certificates configuration for Multi-tenant deployments

### ISSUE THREAD

**Issue by ymgupta** [TheThingsIndustries/lorawan-stack-docs#576]
#### Summary
We see that some of the users are facing issues with generating certificates for the tenants in their multi-tenant deployment while using Let's Encrypt. This is because the tenant addresses are not specified in the `tls.acme.hosts` configuration option, but instead, the base domain address is specified. And so, the certificates are not generated for the tenants in their deployment.

#### Why do we need this?
Users should be able to configure TLS with Let’s Encrypt for multi-tenant deployments.

#### What is already there? What do you see now?
The [Installing The Things Stack](https://www.thethingsindustries.com/docs/getting-started/installation/) documentation has [Certificates](https://www.thethingsindustries.com/docs/getting-started/installation/certificates/) page that has instructions to use Automatic Certificate Management, Using Custom Certificates and also instructions to generate certificates from own Certificate Authority.

#### What is missing? What do you want to see?
Instructions for configuration of TLS with Let’s Encrypt for tenants in Multi-tenant deployments.

#### How do you propose to document this?
Add a Note section [here](https://www.thethingsindustries.com/docs/getting-started/installation/certificates/#automatic-certificate-management) mentioning the below point.

> To configure TLS with Let’s Encrypt for tenants in Multi-tenant deployments, all the tenant addresses have to be specified in the `tls.acme.hosts` configuration option.

Example:
```
tls:
  source: 'acme'
  acme:
    dir: '/var/lib/acme'
    email: 'you@thethings.example.com'
    hosts: ['<tenant1>.thethings.example.com', '<tenant2>.thethings.example.com']
    default-host: 'thethings.example.com'
```
#### Can you do this yourself and submit a Pull Request?
No, @nejraselimovic
