### ISSUE TITLE
Fix TN_LW_NOC_STORE_DATABASE_URI in instructions and docker-compose.yml

### ISSUE THREAD

**Issue by furtiman** [TheThingsIndustries/lorawan-stack-docs#996]
#### Summary

https://www.thethingsindustries.com/docs/getting-started/installation/configuration/#environment-and-ports
The `TTN_LW_NOC_STORE_DATABASE_URI` contains an outdated `postgres://root:root@timescaledb:5432/ttn_lorawan?sslmode=disable`

#### Why do we need this ?

Separate container for `timescaledb` is no longer used

#### What is already there? What do you see now?

In `docker-compose.yml` that is linked [here](https://www.thethingsindustries.com/docs/getting-started/installation/configuration/#example-configuration-files) 
and in the config snippet [here](https://www.thethingsindustries.com/docs/getting-started/installation/configuration/#environment-and-ports)
```
stack:
 ...
  environment:
        TTN_LW_BLOB_LOCAL_DIRECTORY: /srv/ttn-lorawan/public/blob
        TTN_LW_REDIS_ADDRESS: redis:6379
        TTN_LW_IS_DATABASE_URI: postgres://root:root@postgres:5432/ttn_lorawan?sslmode=disable
        TTN_LW_NOC_GRAFANA_NOC_ADDRESS: stack:1884
        TTN_LW_NOC_GRAFANA_TARGET_URL: http://grafana:3000/
        TTN_LW_NOC_STORE_DATABASE_URI: postgres://root:root@timescaledb:5432/ttn_lorawan?sslmode=disable
```

#### What is missing? What do you want to see?

`TTN_LW_NOC_STORE_DATABASE_URI: postgres://root:root@postgres:5432/ttn_lorawan?sslmode=disable` in 
`docker-compose.yml`

#### How do you propose to document this?

Please check consistency in other places this is referenced, including the `ttn-lw-stack-docker.yml`

#### Can you do this yourself and submit a Pull Request?

cc @johanstokking
